# Generated by Django 6.0.6 on 2026-06-12 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_userprofile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
    ]
