# Generated by Django 6.0.6 on 2026-06-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='wrong address', max_length=150),
        ),
    ]
